export default {
    products: [
        {
            _id: '1',
            name: 'Hiskywin Full Zip Running Shirts Thermal Workout',
            category: 'Shirts',
            image: '/images/product-1.png',
            price: 72,
            brand: 'Hiskywin',
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Nike Full-Zip Hoodie Mens Workout Sweatshirt',
            category: 'Shirts',
            image: '/images/product-2.png',
            price: 70,
            brand: 'Nike',
            rating: 5,
            numReviews: 51,
        },
        {
            _id: '3',
            name: 'Adidas Mens Long Sleeve Hoodie',
            category: 'Shirts',
            image: '/images/product-3.png',
            price: 59,
            brand: 'Adidas',
            rating: 4,
            numReviews: 45,
        },
        {
            _id: '4',
            name: 'Under Armour Mens Sportstyle Tricot Joggers',
            category: 'Pants',
            image: '/images/product-4.png',
            price: 90,
            brand: 'Under Armour',
            rating: 2.5,
            numReviews: 198,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Champion Mens Graphic Powerblend Fleece Jogger',
            category: 'Pants',
            image: '/images/product-5.png',
            price: 119,
            brand: 'Champion',
            rating: 3.5,
            numReviews: 89,
            countInStock: 6,
        },
        {
            _id: '6',
            name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
            category: 'Pants',
            image: '/images/product-6.png',
            price: 85,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 6,
        },
        {
            _id: '7',
            name: 'Champion Mens Graphic Powerblend Fleece Jogger',
            category: 'Pants',
            image: '/images/product-7.png',
            price: 129,
            brand: 'Champion',
            rating: 3.5,
            numReviews: 89,
            countInStock: 6,
        },
        {
            _id: '8',
            name: 'Aelfric Eden Mens Joggers Pants Long Multi-Pockets',
            category: 'Pants',
            image: '/images/product-8.png',
            price: 55,
            brand: 'Aelfric Eden',
            rating: 4.5,
            numReviews: 45,
            countInStock: 6,
        },
        {
            _id: '9',
            name: 'Champion Mens Graphic Powerblend Fleece Jogger',
            category: 'Pants',
            image: '/images/product-9.png',
            price: 109,
            brand: 'Champion',
            rating: 3.5,
            numReviews: 89,
            countInStock: 6,
        },
    ],
};